import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

function tempRepo() {
  return mkdtempSync(join(tmpdir(), "amem-instr-"));
}

describe("instruction targets", () => {
  it("covers every selectable platform", async () => {
    const { allInstructionTargets } = await import("../dist/instructions.js");
    const { KNOWN_PLATFORMS } = await import("../dist/platforms.js");
    const targets = allInstructionTargets();
    const covered = new Set(targets.flatMap((t) => t.platforms));
    for (const p of KNOWN_PLATFORMS) {
      if (p.group === "internal") continue;
      assert.ok(covered.has(p.id), `platform ${p.id} has no instruction target`);
    }
  });

  it("writes one shared file instead of one per host", async () => {
    const { allInstructionTargets } = await import("../dist/instructions.js");
    const targets = allInstructionTargets();
    const paths = targets.map((t) => t.path);
    assert.equal(new Set(paths).size, paths.length, "duplicate output paths");
    // AGENTS.md is the fallback for hosts without their own convention, and
    // must be collapsed into a single write.
    const agents = targets.find((t) => t.path === "AGENTS.md");
    assert.ok(agents.platforms.length > 1);
  });

  it("resolves host aliases to the canonical target", async () => {
    const { instructionTargets } = await import("../dist/instructions.js");
    const [target] = instructionTargets(["claude-code"]);
    assert.equal(target.path, "CLAUDE.md");
  });

  it("ignores internal platforms", async () => {
    const { instructionTargets } = await import("../dist/instructions.js");
    assert.deepEqual(instructionTargets(["luna", "app"]), []);
  });
});

describe("rendered instructions", () => {
  it("tells MCP hosts to check the task board first", async () => {
    const { instructionTargets, renderInstructions } = await import("../dist/instructions.js");
    const [claude] = instructionTargets(["claude"]);
    const text = renderInstructions(claude);
    // The point of the whole feature: hosts must know work may already be queued.
    assert.match(text, /amem_task_list/);
    assert.match(text, /amem_task_complete/);
    assert.match(text, /amem_context/);
    assert.match(text, /amem_usage_report/);
  });

  it("gives a CLI-only host commands, not MCP tool names", async () => {
    const { instructionTargets, renderInstructions } = await import("../dist/instructions.js");
    const [aider] = instructionTargets(["aider"]);
    assert.equal(aider.surface, "cli");
    const text = renderInstructions(aider);
    assert.match(text, /amem task list/);
    assert.doesNotMatch(text, /amem_task_list/);
  });

  it("keeps Cursor front matter so the rule actually loads", async () => {
    const { instructionTargets, renderInstructions } = await import("../dist/instructions.js");
    const [cursor] = instructionTargets(["cursor"]);
    const text = renderInstructions(cursor);
    assert.ok(text.startsWith("---\n"));
    assert.match(text, /alwaysApply: true/);
  });

  it("names the hosts it was generated for and promises no memory contents", async () => {
    const { instructionTargets, renderInstructions } = await import("../dist/instructions.js");
    const [copilot] = instructionTargets(["copilot"]);
    const text = renderInstructions(copilot);
    assert.match(text, /Generated by amem for: GitHub Copilot/);
    assert.match(text, /no memory contents/);
  });
});

describe("applying instructions", () => {
  it("creates files and is idempotent", async () => {
    const { applyInstructions, allInstructionTargets } = await import("../dist/instructions.js");
    const root = tempRepo();
    const targets = allInstructionTargets();

    const first = applyInstructions(root, targets);
    assert.ok(first.every((r) => r.status === "written"));

    const second = applyInstructions(root, targets);
    assert.ok(
      second.every((r) => r.status === "unchanged"),
      "re-applying must not rewrite files",
    );
    rmSync(root, { recursive: true, force: true });
  });

  it("appends to a file the user already owns without destroying it", async () => {
    const { applyInstructions, instructionTargets } = await import("../dist/instructions.js");
    const root = tempRepo();
    const path = join(root, "CLAUDE.md");
    writeFileSync(path, "# My Project\n\nUse pnpm, not npm.\n");

    applyInstructions(root, instructionTargets(["claude"]));
    const text = readFileSync(path, "utf8");
    assert.match(text, /Use pnpm, not npm\./);
    assert.match(text, /BEGIN amem/);
    rmSync(root, { recursive: true, force: true });
  });

  it("replaces a stale block instead of stacking a second one", async () => {
    const { applyInstructions, instructionTargets, BEGIN_MARKER, END_MARKER } = await import(
      "../dist/instructions.js"
    );
    const root = tempRepo();
    const path = join(root, "CLAUDE.md");
    writeFileSync(path, `# Mine\n\nkeep me\n\n${BEGIN_MARKER}\nOLD TEXT\n${END_MARKER}\n`);

    applyInstructions(root, instructionTargets(["claude"]));
    const text = readFileSync(path, "utf8");
    assert.doesNotMatch(text, /OLD TEXT/);
    assert.match(text, /keep me/);
    assert.equal(text.split(BEGIN_MARKER).length - 1, 1, "exactly one managed block");
    rmSync(root, { recursive: true, force: true });
  });

  it("dry run reports changes without touching disk", async () => {
    const { applyInstructions, missingInstructions, instructionTargets } = await import(
      "../dist/instructions.js"
    );
    const { existsSync } = await import("node:fs");
    const root = tempRepo();
    const targets = instructionTargets(["claude"]);

    const planned = applyInstructions(root, targets, { dryRun: true });
    assert.equal(planned[0].status, "would-write");
    assert.equal(existsSync(join(root, "CLAUDE.md")), false);

    assert.equal(missingInstructions(root, targets).length, 1);
    applyInstructions(root, targets);
    assert.equal(missingInstructions(root, targets).length, 0);
    rmSync(root, { recursive: true, force: true });
  });
});
