import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { copyBundledSkills, readJsonObject, resolveAmemBin, writeJson } from "./skills.js";
import { readFileSync } from "node:fs";
import { instructionTargets, renderInstructions } from "../instructions.js";

export type InstallResult = {
  skills: string[];
  rulePath?: string;
  hooksPath?: string;
};

function cursorHome(): string {
  return process.env.CURSOR_HOME ?? join(homedir(), ".cursor");
}

function writeCursorRule(repoRoot: string): string {
  const rulesDir = join(repoRoot, ".cursor", "rules");
  mkdirSync(rulesDir, { recursive: true });
  let rulePath = join(rulesDir, "amem.mdc");
  if (existsSync(rulePath)) {
    const existing = readFileSync(rulePath, "utf8");
    if (!existing.includes("Generated by amem")) {
      rulePath = join(rulesDir, "amem-1.mdc");
    }
  }
  // One canonical instruction source for every host — see src/instructions.ts.
  // The old templates/cursor-rule.mdc drifted from what other hosts were told.
  const [target] = instructionTargets(["cursor"]);
  writeFileSync(rulePath, renderInstructions(target!), "utf8");
  return rulePath;
}

function writeCursorHooks(): string {
  const hooksPath = join(cursorHome(), "hooks.json");
  const amem = resolveAmemBin();
  const existing = readJsonObject(hooksPath);
  existing.version = 1;

  const hooks = (existing.hooks as Record<string, unknown>) ?? {};
  const hookCmd = `${amem} hook`;
  const entry = {
    command: hookCmd,
    description: "amem: inject and store local memory (Generated by amem)",
  };

  const filterAmem = (entries: unknown[]) =>
    entries.filter((e) => {
      if (!e || typeof e !== "object") return true;
      const desc = (e as { description?: string }).description ?? "";
      const command = (e as { command?: string }).command ?? "";
      return !desc.includes("Generated by amem") && !command.includes("amem session touch") && !command.includes("amem hook");
    });

  for (const event of ["sessionStart", "beforeSubmitPrompt", "afterAgentResponse", "stop", "sessionEnd"] as const) {
    const current = Array.isArray(hooks[event]) ? (hooks[event] as unknown[]) : [];
    hooks[event] = [...filterAmem(current), entry];
  }

  existing.hooks = hooks;
  writeJson(hooksPath, existing);
  return hooksPath;
}

export function installCursor(repoRoot: string): InstallResult {
  const skills = copyBundledSkills(join(cursorHome(), "skills"));
  const rulePath = writeCursorRule(repoRoot);
  const hooksPath = writeCursorHooks();
  return { skills, rulePath, hooksPath };
}

export function cursorInstallHealth(repoRoot: string): string[] {
  const issues: string[] = [];
  const skill = join(cursorHome(), "skills", "amem-bootstrap", "SKILL.md");
  if (!existsSync(skill)) issues.push(`Missing Cursor skill: ${skill}`);
  const rule = join(repoRoot, ".cursor", "rules", "amem.mdc");
  const ruleAlt = join(repoRoot, ".cursor", "rules", "amem-1.mdc");
  if (!existsSync(rule) && !existsSync(ruleAlt)) {
    issues.push(`Missing Cursor rule under ${join(repoRoot, ".cursor", "rules")}`);
  }
  const hooksPath = join(cursorHome(), "hooks.json");
  if (!existsSync(hooksPath)) {
    issues.push(`Missing Cursor hooks: ${hooksPath}`);
  } else {
    const raw = readFileSync(hooksPath, "utf8");
    // PATH install: `…/amem hook`; linked-from-source: `node …/cli.js hook`
    const hasHook =
      raw.includes("amem hook") ||
      /cli\.js\s+hook/.test(raw) ||
      raw.includes("Generated by amem");
    if (!hasHook) {
      issues.push("Cursor hooks.json does not call `amem hook` — re-run amem init --platform cursor");
    }
  }
  return issues;
}
