import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import {
  copyBundledSkills,
  readJsonObject,
  resolveAmemBin,
  templatePath,
  writeJson,
} from "./skills.js";
import { readFileSync } from "node:fs";

export type InstallResult = {
  skills: string[];
  rulePath?: string;
  hooksPath?: string;
};

function cursorHome(): string {
  return process.env.CURSOR_HOME ?? join(homedir(), ".cursor");
}

function writeCursorRule(repoRoot: string): string {
  const rulesDir = join(repoRoot, ".cursor", "rules");
  mkdirSync(rulesDir, { recursive: true });
  let rulePath = join(rulesDir, "amem.mdc");
  if (existsSync(rulePath)) {
    const existing = readFileSync(rulePath, "utf8");
    if (!existing.includes("Generated by amem")) {
      rulePath = join(rulesDir, "amem-1.mdc");
    }
  }
  const template = readFileSync(templatePath("cursor-rule.mdc"), "utf8");
  writeFileSync(rulePath, template, "utf8");
  return rulePath;
}

function writeCursorHooks(): string {
  const hooksPath = join(cursorHome(), "hooks.json");
  const amem = resolveAmemBin();
  const existing = readJsonObject(hooksPath);

  const hooks = (existing.hooks as Record<string, unknown>) ?? {};
  const before = Array.isArray(hooks.beforeSubmitPrompt)
    ? (hooks.beforeSubmitPrompt as unknown[])
    : [];
  const stop = Array.isArray(hooks.stop) ? (hooks.stop as unknown[]) : [];

  const trackCmd = `${amem} session touch --platform cursor`;
  const beforeEntry = {
    command: trackCmd,
    description: "amem: track session (Generated by amem)",
  };
  const stopEntry = {
    command: trackCmd,
    description: "amem: track session stop (Generated by amem)",
  };

  const filterAmem = (entries: unknown[]) =>
    entries.filter((e) => {
      if (!e || typeof e !== "object") return true;
      const desc = (e as { description?: string }).description ?? "";
      return !desc.includes("Generated by amem");
    });

  hooks.beforeSubmitPrompt = [...filterAmem(before), beforeEntry];
  hooks.stop = [...filterAmem(stop), stopEntry];
  existing.hooks = hooks;
  writeJson(hooksPath, existing);
  return hooksPath;
}

export function installCursor(repoRoot: string): InstallResult {
  const skills = copyBundledSkills(join(cursorHome(), "skills"));
  const rulePath = writeCursorRule(repoRoot);
  const hooksPath = writeCursorHooks();
  return { skills, rulePath, hooksPath };
}

export function cursorInstallHealth(repoRoot: string): string[] {
  const issues: string[] = [];
  const skill = join(cursorHome(), "skills", "amem-bootstrap", "SKILL.md");
  if (!existsSync(skill)) issues.push(`Missing Cursor skill: ${skill}`);
  const rule = join(repoRoot, ".cursor", "rules", "amem.mdc");
  const ruleAlt = join(repoRoot, ".cursor", "rules", "amem-1.mdc");
  if (!existsSync(rule) && !existsSync(ruleAlt)) {
    issues.push(`Missing Cursor rule under ${join(repoRoot, ".cursor", "rules")}`);
  }
  return issues;
}
