/**
 * Compile pinned facts into a local Cursor rule file.
 * Default writes into the repo .cursor/rules folder. Memory DB is unchanged.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { listClaims, type RepoRow } from "./db.js";
import { parseAnchors } from "./freshness.js";
import { FEATURE_RULES_SYNC, requireFeature } from "./license.js";

export function pinnedRulesPath(repoRoot: string): string {
  return join(repoRoot, ".cursor", "rules", "amem-pinned.mdc");
}

export function renderPinnedRules(repo: RepoRow): string {
  const pinned = listClaims(repo.id).filter((c) => Number(c.pinned || 0) > 0);
  const lines = [
    "---",
    "description: Pinned amem facts. Generated — review before committing.",
    "alwaysApply: true",
    "---",
    "",
    "<!-- Generated by amem. Contains no memory database. Safe to gitignore. -->",
    "",
    `# Pinned memory for ${repo.repo_name}`,
    "",
  ];
  if (pinned.length === 0) {
    lines.push("_No pinned facts._", "");
  } else {
    for (const claim of pinned) {
      const anchors = parseAnchors(claim.code_anchors);
      const where = anchors.length ? ` — \`${anchors.join("`, `")}\`` : "";
      lines.push(`- **${claim.kind}** ${claim.text.trim()}${where}`);
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

export function syncPinnedRules(repo: RepoRow): { path: string; pinned: number } {
  requireFeature(FEATURE_RULES_SYNC, "Cursor rule sync");
  const path = pinnedRulesPath(repo.root_path);
  mkdirSync(join(repo.root_path, ".cursor", "rules"), { recursive: true });
  const body = renderPinnedRules(repo);
  writeFileSync(path, body, "utf8");
  const pinned = listClaims(repo.id).filter((c) => Number(c.pinned || 0) > 0).length;
  return { path, pinned };
}
