import { existsSync, mkdirSync, unlinkSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { amemHome } from "./paths.js";
import { resolveAmemProgramArgs } from "./install/skills.js";

export const SERVICE_LABEL = "co.amem.ui";
export const SYSTEMD_UNIT = "amem-ui.service";

export type ServicePlatform = "darwin" | "linux" | "win32" | "unsupported";

export function servicePlatform(): ServicePlatform {
  if (process.platform === "darwin") return "darwin";
  if (process.platform === "linux") return "linux";
  if (process.platform === "win32") return "win32";
  return "unsupported";
}

export function isServiceSupported(): boolean {
  return servicePlatform() !== "unsupported";
}

export function launchAgentPath(): string {
  return join(homedir(), "Library", "LaunchAgents", `${SERVICE_LABEL}.plist`);
}

export function systemdUserUnitPath(): string {
  return join(homedir(), ".config", "systemd", "user", SYSTEMD_UNIT);
}

export function windowsStartupCmdPath(): string {
  const appData = process.env.APPDATA || join(homedir(), "AppData", "Roaming");
  return join(appData, "Microsoft", "Windows", "Start Menu", "Programs", "Startup", "amem-ui.cmd");
}

export function serviceInstallPath(): string {
  const p = servicePlatform();
  if (p === "darwin") return launchAgentPath();
  if (p === "linux") return systemdUserUnitPath();
  if (p === "win32") return windowsStartupCmdPath();
  return "";
}

export function isServiceInstalled(): boolean {
  const path = serviceInstallPath();
  return Boolean(path && existsSync(path));
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function programCommandLine(): { args: string[]; shellLine: string } {
  const args = resolveAmemProgramArgs("ui", "--no-open");
  const shellLine = args.map((a) => (/\s/.test(a) ? `"${a.replace(/"/g, '\\"')}"` : a)).join(" ");
  return { args, shellLine };
}

function plistBody(): string {
  const { args } = programCommandLine();
  const argXml = args.map((a) => `    <string>${escapeXml(a)}</string>`).join("\n");
  const logs = amemHome();
  const pathEnv = ["/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin"].join(":");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${SERVICE_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${argXml}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>WorkingDirectory</key>
  <string>${escapeXml(homedir())}</string>
  <key>StandardOutPath</key>
  <string>${escapeXml(join(logs, "ui.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(join(logs, "ui.err.log"))}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>${escapeXml(pathEnv)}</string>
  </dict>
</dict>
</plist>
`;
}

function systemdUnitBody(): string {
  const { shellLine } = programCommandLine();
  const logs = amemHome();
  return `[Unit]
Description=amem local UI (loopback only)
After=default.target

[Service]
Type=simple
ExecStart=${shellLine}
WorkingDirectory=${homedir()}
Restart=on-failure
RestartSec=3
StandardOutput=append:${join(logs, "ui.log")}
StandardError=append:${join(logs, "ui.err.log")}
Environment=PATH=/usr/local/bin:/usr/bin:/bin:${homedir()}/.local/bin

[Install]
WantedBy=default.target
`;
}

function windowsCmdBody(): string {
  const { shellLine } = programCommandLine();
  return `@echo off\r\nrem amem local UI (Generated by amem)\r\nstart "" /B ${shellLine}\r\n`;
}

function uid(): string {
  return String(process.getuid?.() ?? "");
}

function launchctl(args: string[]): void {
  execFileSync("launchctl", args, { stdio: ["ignore", "pipe", "pipe"] });
}

function systemctlUser(args: string[]): void {
  execFileSync("systemctl", ["--user", ...args], { stdio: ["ignore", "pipe", "pipe"] });
}

function installDarwin(): { path: string; installed: boolean } {
  const path = launchAgentPath();
  mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
  writeFileSync(path, plistBody(), "utf8");
  const domain = `gui/${uid()}`;
  try {
    launchctl(["bootout", domain, path]);
  } catch {
    // not loaded yet
  }
  try {
    launchctl(["bootstrap", domain, path]);
  } catch {
    try {
      launchctl(["load", "-w", path]);
    } catch {
      // plist is on disk; next login still picks it up
    }
  }
  return { path, installed: true };
}

function uninstallDarwin(): { path: string; installed: boolean } {
  const path = launchAgentPath();
  if (existsSync(path)) {
    try {
      launchctl(["bootout", `gui/${uid()}`, path]);
    } catch {
      try {
        launchctl(["unload", "-w", path]);
      } catch {
        // ignore
      }
    }
    unlinkSync(path);
  }
  return { path, installed: false };
}

function installLinux(): { path: string; installed: boolean } {
  const path = systemdUserUnitPath();
  mkdirSync(join(homedir(), ".config", "systemd", "user"), { recursive: true });
  mkdirSync(amemHome(), { recursive: true });
  writeFileSync(path, systemdUnitBody(), "utf8");
  try {
    systemctlUser(["daemon-reload"]);
  } catch {
    // unit file still valid for next login / manual start
  }
  try {
    systemctlUser(["enable", "--now", SYSTEMD_UNIT]);
  } catch {
    try {
      systemctlUser(["enable", SYSTEMD_UNIT]);
    } catch {
      // enabled-at-login may require lingering; file is installed
    }
  }
  return { path, installed: true };
}

function uninstallLinux(): { path: string; installed: boolean } {
  const path = systemdUserUnitPath();
  try {
    systemctlUser(["disable", "--now", SYSTEMD_UNIT]);
  } catch {
    try {
      systemctlUser(["disable", SYSTEMD_UNIT]);
    } catch {
      // ignore
    }
  }
  if (existsSync(path)) unlinkSync(path);
  try {
    systemctlUser(["daemon-reload"]);
  } catch {
    // ignore
  }
  return { path, installed: false };
}

function installWindows(): { path: string; installed: boolean } {
  const path = windowsStartupCmdPath();
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, windowsCmdBody(), "utf8");
  try {
    chmodSync(path, 0o644);
  } catch {
    // windows may ignore mode
  }
  return { path, installed: true };
}

function uninstallWindows(): { path: string; installed: boolean } {
  const path = windowsStartupCmdPath();
  if (existsSync(path)) unlinkSync(path);
  return { path, installed: false };
}

export function installLoginService(): { path: string; installed: boolean; platform: ServicePlatform } {
  const platform = servicePlatform();
  if (platform === "darwin") return { ...installDarwin(), platform };
  if (platform === "linux") return { ...installLinux(), platform };
  if (platform === "win32") return { ...installWindows(), platform };
  throw new Error("Login auto-start is not supported on this OS.");
}

export function uninstallLoginService(): { path: string; installed: boolean; platform: ServicePlatform } {
  const platform = servicePlatform();
  if (platform === "darwin") return { ...uninstallDarwin(), platform };
  if (platform === "linux") return { ...uninstallLinux(), platform };
  if (platform === "win32") return { ...uninstallWindows(), platform };
  return { path: serviceInstallPath(), installed: false, platform };
}
